[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "qimview"
version = "1.0.0"
authors = [
  { name="Karl Krissian", email="karl.krissian@gmail.com" },
]
description = "Library for multiple image visualization and comparison"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache 2",
    "Operating System :: OS Independent",
]

dependencies = [
    "CppBind>=1.0.3",
    "cppimport>=20.8.4.2",
    "numpy>=1.19.4",
    "opencv_python>=4.4.0.46",
    "psutil>=5.8.0",
    "pygame>=2.0.0",
    "PyOpenGL>=3.1.7",
    "pyqtgraph>=0.11.0",
    "PySide6>=6.5.2",
    "PySide6_Addons>=6.5.1.1",
    "PySide6_Essentials>=6.5.1.1",
    "python_vlc>=3.0.11115",
    "PyTurboJPEG>=1.4.1",
    "Qt.py_stubs>=0.0.1",
    "rawpy>=0.16.0",
    "scipy>=1.6.0",
    "simplejpeg>=1.4.0"
]

[project.urls]
"Homepage" = "https://github.com/karlkrissian/qimview"
"Bug Tracker" = "https://github.com/karlkrissian/qimview/issues"

# [tool.setuptools]
# py-modules = []
